DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT`
(
    `ID`          INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USERNAME`    VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '帐号',
    `PASSWORD`    VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '密码',
    `CREATE_DATE` DATE COMMENT '注册日期',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4;

TRUNCATE TABLE `ACCOUNT`;

INSERT INTO `ACCOUNT` (`USERNAME`, `PASSWORD`, `CREATE_DATE`)
VALUES ('COMMIT', 'COMMIT', NOW());
COMMIT;

INSERT INTO `ACCOUNT` (`USERNAME`, `PASSWORD`, `CREATE_DATE`)
VALUES ('ROLLBACK', 'ROLLBACK', NOW());
ROLLBACK;

INSERT INTO `ACCOUNT`
VALUES (5, 'ADMIN', 'ADMIN', NOW());
COMMIT;

INSERT INTO `ACCOUNT` (`USERNAME`, `PASSWORD`, `CREATE_DATE`)
VALUES ('U001', 'P001', NOW()),
       ('U002', 'P002', NOW()),
       ('U003', 'P003', NOW()),
       ('U004', 'P004', NOW()),
       ('U005', 'P005', NOW());
COMMIT;

DELETE FROM `ACCOUNT` WHERE `USERNAME` = 'ROLLBACK';
COMMIT;

UPDATE `ACCOUNT` SET `PASSWORD` = 'PPP' WHERE `USERNAME` like 'U%';
COMMIT;