DROP TABLE IF EXISTS `USER_A`;
CREATE TABLE `USER_A`
(
    `ID`    INT,
    `NAME`  VARCHAR(50),
    `PHONE` CHAR(11)
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

ALTER TABLE `USER_A`
    ADD INDEX I_01 (PHONE);
ALTER TABLE `USER_A`
    ADD UNIQUE (NAME);
ALTER TABLE `USER_A`
    ADD PRIMARY KEY (ID);

# ALTER TABLE `USER_A` DROP INDEX NAME_2;

SHOW INDEX FROM `USER_A`;

DROP TABLE IF EXISTS `USER_B`;
CREATE TABLE `USER_B`
(
    `ID`    INT,
    `NAME`  VARCHAR(50),
    `PHONE` CHAR(11)
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

CREATE INDEX I_02 ON `USER_B` (PHONE);
CREATE UNIQUE INDEX U_02 ON `USER_B` (NAME);

# DROP INDEX U_03 ON `USER_B`;

SHOW INDEX FROM `USER_B`;

REPAIR TABLE `USER_A` QUICK;
REPAIR TABLE `USER_B` QUICK;

DROP TABLE IF EXISTS `USER_C`;
CREATE TABLE `USER_C`
(
    `A` INT,
    `B` INT,
    `C` INT
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

CREATE INDEX I_ABC ON `USER_C` (A, B, C);
SHOW INDEX FROM `USER_C`;

-- Index A effective
SELECT *
FROM `USER_C`
WHERE A = 1;

-- Index A,B effective
SELECT *
FROM `USER_C`
WHERE A = 1
   OR B = 2;

-- Index A,B,C effective
SELECT *
FROM `USER_C`
WHERE A = 1
   OR B = 2
   OR C = 3;

-- Index A,B,C failure
SELECT *
FROM `USER_C`
WHERE B = 2
   OR C = 3;

-- Index A effective abd index C failure
SELECT *
FROM `USER_C`
WHERE A = 2
   OR C = 3;
