SELECT NOW(), CURDATE(), CURTIME()
FROM DUAL;

SELECT NOW(), CURDATE(), CURTIME();

SELECT NOW(), DATE_ADD('2018-08-08', INTERVAL 10 DAY);

SELECT NOW(), DATE_SUB(NOW(), INTERVAL 10 MONTH);

SELECT DATEDIFF('2018-08-08', '2008-08-08');

SELECT DATE_FORMAT(NOW(), '%Y-%M-%D %T');

SELECT EXTRACT(MONTH FROM '2016-09-09');

SELECT MONTH(now());

SELECT LAST_DAY(NOW());