SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'MARTIN');

SELECT ENAME, SAL
FROM EMP
WHERE SAL > ANY (SELECT SAL FROM EMP WHERE DEPTNO = 10);

SELECT ENAME, SAL
FROM EMP
WHERE SAL = SOME (SELECT SAL FROM EMP WHERE DEPTNO = 10);

SELECT ENAME, SAL
FROM EMP
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO = 20);

SELECT DEPTNO, DNAME
FROM DEPT
WHERE EXISTS(SELECT 1 FROM EMP WHERE EMP.DEPTNO = DEPT.DEPTNO);

SELECT DEPTNO, DNAME
FROM DEPT
WHERE NOT EXISTS(SELECT 1 FROM EMP WHERE EMP.DEPTNO = DEPT.DEPTNO);