SELECT EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E
         JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E
         INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E
         LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, D.DEPTNO, DNAME
FROM EMP E
         RIGHT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT XIAO.ENAME, DA.ENAME
FROM EMP XIAO
         JOIN EMP DA ON DA.EMPNO = XIAO.MGR;
