SELECT ENAME,
       SAL,
       CASE
           WHEN SAL BETWEEN 800 AND 1500 THEN '穷人'
           WHEN SAL BETWEEN 1501 AND 3000 THEN '小康'
           ELSE '富人'
           END
           RESULT
FROM EMP
WHERE SAL IS NOT NULL
ORDER BY SAL;

SELECT COMM, IFNULL(COMM, 0) RESULT
FROM EMP;

SELECT COMM, IF(COMM, 'YES', 'NO') RESULT
FROM EMP;

SELECT DEPTNO, IF(DEPTNO = 20, 'DEPT-20', 'OTHER') RESULT
FROM EMP;

SELECT DEPTNO,
       IF(DEPTNO = 10, 'DEPT-10',
          IF(DEPTNO = 20, 'DEPT-20',
             IF(DEPTNO = 30, 'DEPT-30', 'DEPT-40'))) RESULT
FROM EMP;