DROP TABLE IF EXISTS `CLASS`;

CREATE TABLE `CLASS`
(
    `ID`   INT,
    `NAME` VARCHAR(50) NOT NULL,
    `LOC`  VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE (NAME)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4;

INSERT INTO `CLASS`
VALUES (1, 'J500', '北京'),
       (2, 'J501', '上海'),
       (3, 'J502', '广州'),
       (4, 'J503', '深圳');
COMMIT;

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'CLASS'