DROP TABLE `ACCOUNT`;
CREATE TABLE `ACCOUNT`
(
    `ID`          INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USERNAME`    VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '帐号',
    `PASSWORD`    VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '密码',
    `CREATE_DATE` DATE COMMENT '注册日期',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4;

SHOW CREATE TABLE `EMP`;

DESC `ACCOUNT`;

SHOW COLUMNS FROM `ACCOUNT`;

SHOW INDEX FROM `ACCOUNT`;

SHOW TABLE STATUS LIKE '%ACCOUNT%';

RENAME TABLE `ACCOUNT` TO `ACCOUNT_JOE`;

TRUNCATE TABLE `ACCOUNT`;

ALTER TABLE `ACCOUNT`
    ADD TEST_COLUMN CHAR(4);

ALTER TABLE `ACCOUNT`
    MODIFY TEST_COLUMN VARCHAR(4);

ALTER TABLE `ACCOUNT`
    DROP COLUMN TEST_COLUMN;

CREATE TABLE `EMP_COPY`(
    SELECT *
    FROM EMP
);

DROP TABLE `TEMP`;
CREATE TEMPORARY TABLE `TEMP`
(
    `COLUMN_A` VARCHAR(50)    NOT NULL,
    `COLUMN_B` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    `COLUMN_C` INT UNSIGNED   NOT NULL DEFAULT 0
);

SELECT *
FROM `TEMP`;