DROP TABLE IF EXISTS `CLASS`;
CREATE TABLE `CLASS`
(
    `ID`   INT PRIMARY KEY,
    `NAME` VARCHAR(30) NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4;

DROP TABLE IF EXISTS `STUDENT_A`;
CREATE TABLE `STUDENT_A`
(
    `ID`    INT PRIMARY KEY,
    `NAME`  VARCHAR(50) NOT NULL,
    `PHONE` CHAR(11) UNIQUE
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

DROP TABLE IF EXISTS `STUDENT_B`;
CREATE TABLE `STUDENT_B`
(
    `ID`       INT,
    `PHONE`    CHAR(11),
    `CLASS_ID` INT,
    UNIQUE (PHONE),
    PRIMARY KEY (ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS (ID)
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

DROP TABLE IF EXISTS `STUDENT_C`;
CREATE TABLE `STUDENT_C`
(
    `ID`       INT,
    `NAME`     VARCHAR(50),
    `PHONE`    CHAR(11),
    `CLASS_ID` INT
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

ALTER TABLE `STUDENT_C`
    MODIFY `NAME` VARCHAR(50) NOT NULL;
ALTER TABLE `STUDENT_C`
    ADD CONSTRAINT UK_01 UNIQUE (PHONE);
ALTER TABLE `STUDENT_C`
    ADD CONSTRAINT UK_02 UNIQUE (NAME, PHONE);
ALTER TABLE `STUDENT_C`
    ADD CONSTRAINT PK_01 PRIMARY KEY (ID);
ALTER TABLE `STUDENT_C`
    ADD CONSTRAINT FK_01 FOREIGN KEY (CLASS_ID) REFERENCES CLASS (ID);

DROP TABLE IF EXISTS `STUDENT_D`;
CREATE TABLE `STUDENT_D`
(
    `ID`       INT,
    `NAME`     VARCHAR(50),
    `PHONE`    CHAR(11),
    `CLASS_ID` INT
)
    ENGINE = INNODB
    DEFAULT CHARSET = UTF8MB4;

ALTER TABLE `STUDENT_D`
    MODIFY `NAME` VARCHAR(50) NOT NULL;
ALTER TABLE `STUDENT_D`
    ADD UNIQUE (PHONE);
ALTER TABLE `STUDENT_D`
    ADD PRIMARY KEY (ID);
ALTER TABLE `STUDENT_D`
    ADD FOREIGN KEY (CLASS_ID) REFERENCES CLASS (ID);

SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME IN ('STUDENT_A', 'STUDENT_B', 'STUDENT_C', 'STUDENT_D');

DESC `STUDENT_A`;
DESC `STUDENT_B`;
DESC `STUDENT_C`;
DESC `STUDENT_D`;

ALTER TABLE `STUDENT_C`
    DROP PRIMARY KEY;
ALTER TABLE `STUDENT_C`
    DROP KEY UK_01;
ALTER TABLE `STUDENT_C`
    DROP INDEX UK_01;
ALTER TABLE `STUDENT_C`
    DROP FOREIGN KEY FK_01;